In [74]:
import pandas as pd
import numpy as np
from scipy.stats import shapiro, ttest_ind, chi2_contingency, fisher_exact

In [2]:
df = pd.read_csv('heart_disease_uci.csv')

In [3]:
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [5]:
100 * df.isnull().sum()/ len(df)

id           0.000000
age          0.000000
sex          0.000000
dataset      0.000000
cp           0.000000
trestbps     6.413043
chol         3.260870
fbs          9.782609
restecg      0.217391
thalch       5.978261
exang        5.978261
oldpeak      6.739130
slope       33.586957
ca          66.413043
thal        52.826087
num          0.000000
dtype: float64

In [9]:
df['trestbps'] = df['trestbps'].fillna(df['trestbps'].median())

In [11]:
df['chol'] = df['chol'].fillna(df['chol'].median())

In [16]:
df['fbs'] = df['fbs'].fillna(df['fbs'].mode()[0])

In [20]:
df['restecg'] = df['restecg'].fillna(df['restecg'].mode()[0])

In [21]:
df['thalch'] = df['thalch'].fillna(df['thalch'].median())

In [25]:
df['exang'] = df['exang'].fillna(df['exang'].mode()[0])

In [29]:
df['oldpeak'] = df['oldpeak'].fillna(df['oldpeak'].median())

In [36]:
df['slope'] = df['slope'].fillna(df['slope'].mode()[0])

In [35]:
df['ca'] = df['ca'].fillna(df['ca'].median())

In [39]:
df['thal'] = df['thal'].fillna(df['thal'].mode()[0])

In [40]:
100 * df.isnull().sum()/ len(df)

id          0.0
age         0.0
sex         0.0
dataset     0.0
cp          0.0
trestbps    0.0
chol        0.0
fbs         0.0
restecg     0.0
thalch      0.0
exang       0.0
oldpeak     0.0
slope       0.0
ca          0.0
thal        0.0
num         0.0
dtype: float64

In [41]:
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [43]:
df = df.drop('id', axis=1)

In [44]:
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

#Shapiro-Wilk

Hypothèse:
Ho: La variable âge suis une loi normale

In [47]:
homme = df[df['sex'] == 'Male']

In [57]:
femme = df[df['sex'] == 'Female']

In [54]:
stats, p = shapiro(df['age'])

In [55]:
p

np.float64(2.267545265256918e-05)

La variable âge ne suis pas une loi normale car p <= 0.05 donc Ho est rejétéé

#Test d'indépendance

In [62]:
stats, p = ttest_ind(homme['age'], femme['age'])

In [63]:
p

np.float64(1.0)

Pas de preuve que l'âge a d'effet sur le fait d'aoir la maladie ou pas

#Khi-deux

Hypothèse:
1.   Ho: La variable sexe et slope sont liées
2.   H1: La variable sexe et slope ne sont pas liées

In [78]:
stats, p, dof, expected = chi2_contingency(pd.crosstab(df['sex'], df['slope']))

In [79]:
p

np.float64(0.005781486883537746)

p < 0.05 alors l'hypothèse Ho est accepté et H1 est rejeté. On peut donc conclu que les variables sex et slope sont liées.

#Fisher

In [84]:
stats, p = fisher_exact(pd.crosstab(df['sex'], df['slope']))

In [85]:
p

np.float64(0.0062)

Ceci viens de confirmer encore plus l'hypothèse du test de Khi-deux